version: "3.8"
services:
  db:
    image:postgres
    environment:
      POSTGRES_PASSWORD: fadil123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: app-nodejs1
    depends_on:
      - db
    ports:
      - "4000:4000"      